### ISSUE TITLE
Sensory powinny pokazywać aktualną liczbę paczek w danym statusie

### ISSUE THREAD

**Issue by stemer77** [Przemko92/home-assistant-allegro#1]
Będzie po polsku, ale jak mam napisać po angielsku, to proszę dać znać.
Integracja zainstalowana w HA 2023.1.7, supervisor 2023.01.1, całość na x86_64 z custom repository.
Skoro integracja eksponuje 4 sensory o statusach danej paczki, to oczekuję, że będą one pokazywać liczbę paczek w danym statusie.
Zakupiłem przedmiot z Allegro i encja sensor.allegro_xxxallegrousernamexxx_in_progress bezbłędnie pokazała wartość 1. Następnie paczka została tego samego dnia podjęta przez Inpost i encja sensor.allegro_xxxallegrousernamexxx_in_transit pokazała wartość 1, ale encja sensor.allegro_xxxallegrousernamexxx_in_progress już nie pokazała oczekiwanego 0. Oczekiwanym działaniem byłaby zmiana encji sensor.allegro_stemer_in_progress na 0 w przypadku jednej paczki (lub zmniejszenie jej wartości o liczbę paczek, które przeszły w in_progress).

**Comment by Przemko92** [comment]
Sensor in progress pokazuje wszystkie paczki w statusie innym, niż doręczony. Tam będziesz widział także zwroty i niestandardowe statusy paczek (np. nie odebrano paczki, zly adres itp.).  
Jeśli chcesz osiągnąć taki efekt, jak piszesz, musisz odjąć od tej wartosci wszystkie wysłane paczki.

**Comment by stemer77** [comment]
Dzięki, to ma sens. Dzisiaj zgodnie z oczekiwaniem zachowały się sensory transit i delivery.
